# .github/workflows/cron-job.yml

name: My Cron Job

on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      SOURCE_DB_URL: ${{ secrets.SOURCE_DB_URL }}
      TARGET_DB_URL: ${{ secrets.TARGET_DB_URL }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: python datapipeline.py
